run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Examine Go source code and reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # State-of-the-art linter
    - unused        # Check for unused constants, variables, functions and types
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import statements are formatted
    - misspell      # Check for misspelled English words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - unparam       # Reports unused function parameters
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - shadow        # Reports variables that shadow other variables
      - fieldalignment # Field alignment is a micro-optimization that can reduce code readability

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  goimports:
    local-prefixes: github.com/mateimicu/tmux-claude-fleet

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - unparam

output:
  sort-results: true
